[package]
name = "ews-calendar"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
surf = "2.3"
anyhow = "1"
chrono = "0.4"
base64 = "0.13"
xml-rs = "0.8"
derive_builder = "0.10"


[dev-dependencies]
async-std = { version = "1.10", features = ["attributes"] }
